# fly.toml app configuration file generated for plezalni-vodic on 2023-12-17T21:24:27+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "plezalni-vodic"
primary_region = "ams"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
